// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7IGrKKNXWW9zU2-EC4rwT8Jh5rB5HBrQ',
    appId: '1:748777517673:web:4f65c5763e5123877128f8',
    messagingSenderId: '748777517673',
    projectId: 'rrhh-psicologia-app',
    authDomain: 'rrhh-psicologia-app.firebaseapp.com',
    databaseURL: 'https://rrhh-psicologia-app-default-rtdb.firebaseio.com',
    storageBucket: 'rrhh-psicologia-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCOAs27FzU8KfbXo5GG0kEXnHXeKRkeQA',
    appId: '1:748777517673:android:cf2ef607c79635c07128f8',
    messagingSenderId: '748777517673',
    projectId: 'rrhh-psicologia-app',
    databaseURL: 'https://rrhh-psicologia-app-default-rtdb.firebaseio.com',
    storageBucket: 'rrhh-psicologia-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXyNF5BzshonaY9yf_xhsbALSXU6sS85U',
    appId: '1:748777517673:ios:52b2435194db07737128f8',
    messagingSenderId: '748777517673',
    projectId: 'rrhh-psicologia-app',
    databaseURL: 'https://rrhh-psicologia-app-default-rtdb.firebaseio.com',
    storageBucket: 'rrhh-psicologia-app.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXyNF5BzshonaY9yf_xhsbALSXU6sS85U',
    appId: '1:748777517673:ios:52b2435194db07737128f8',
    messagingSenderId: '748777517673',
    projectId: 'rrhh-psicologia-app',
    databaseURL: 'https://rrhh-psicologia-app-default-rtdb.firebaseio.com',
    storageBucket: 'rrhh-psicologia-app.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7IGrKKNXWW9zU2-EC4rwT8Jh5rB5HBrQ',
    appId: '1:748777517673:web:9a19784ea8336fd97128f8',
    messagingSenderId: '748777517673',
    projectId: 'rrhh-psicologia-app',
    authDomain: 'rrhh-psicologia-app.firebaseapp.com',
    databaseURL: 'https://rrhh-psicologia-app-default-rtdb.firebaseio.com',
    storageBucket: 'rrhh-psicologia-app.firebasestorage.app',
  );

}