// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChx8q1qXEqaynDAlhe1sgJG1vBi9dtMEs',
    appId: '1:469737058944:web:4d3cee11539262d85dac65',
    messagingSenderId: '469737058944',
    projectId: 'reg-de-cap-y-ev-psico',
    authDomain: 'reg-de-cap-y-ev-psico.firebaseapp.com',
    storageBucket: 'reg-de-cap-y-ev-psico.firebasestorage.app',
    measurementId: 'G-BMF424G8YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw_BWSrJBHmM5tceJhE65kEmUuFilNLvI',
    appId: '1:469737058944:android:f078e8ed1a684c255dac65',
    messagingSenderId: '469737058944',
    projectId: 'reg-de-cap-y-ev-psico',
    storageBucket: 'reg-de-cap-y-ev-psico.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuXL3bwZp1c3KT_0vnbZfHyZjXFPZ_Mhc',
    appId: '1:469737058944:ios:d5a6de4e157fa03b5dac65',
    messagingSenderId: '469737058944',
    projectId: 'reg-de-cap-y-ev-psico',
    storageBucket: 'reg-de-cap-y-ev-psico.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuXL3bwZp1c3KT_0vnbZfHyZjXFPZ_Mhc',
    appId: '1:469737058944:ios:d5a6de4e157fa03b5dac65',
    messagingSenderId: '469737058944',
    projectId: 'reg-de-cap-y-ev-psico',
    storageBucket: 'reg-de-cap-y-ev-psico.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChx8q1qXEqaynDAlhe1sgJG1vBi9dtMEs',
    appId: '1:469737058944:web:edacc3cdb6639ffb5dac65',
    messagingSenderId: '469737058944',
    projectId: 'reg-de-cap-y-ev-psico',
    authDomain: 'reg-de-cap-y-ev-psico.firebaseapp.com',
    storageBucket: 'reg-de-cap-y-ev-psico.firebasestorage.app',
    measurementId: 'G-7EDE1RYR6D',
  );
}
